
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Logstashbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-logstashbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-logstashbeat]]
== Logstashbeat Fields

Logstashbeat fields.



[float]
== events Fields

Contains events metrics.



[float]
=== events.in

type: long

Number of events just accepted.


[float]
=== events.out

type: long

Number of currently processed events.


[float]
=== events.filter

type: long

Number of currently filtered events.


[float]
== jvm Fields

Contains fields available for JVM



[float]
== threads Fields

Contains fields available for JVM



[float]
=== jvm.threads.count

type: long

Threads count.


[float]
=== jvm.threads.peak_count

type: long

Peak count threads.


[float]
== process Fields

Contains fields process metrics.



[float]
=== process.max_file_descriptors

type: integer

Maximum file descriptors.


[float]
=== process.open_file_descriptors

type: integer

Open file descriptors.


[float]
=== process.peak_open_file_descriptors

type: integer

Peak open file descriptors.


[float]
== cpu Fields

Contains CPU statistics



[float]
=== process.cpu.percent

type: long

CPU percent.


[float]
=== process.cpu.total_in_millis

type: long

CPU total time in miliseconds.


[float]
== mem Fields

Contains memory metrics.



[float]
=== process.mem.total_virtual_in_bytes

type: float

Total virtual memory in bytes.


